# Generated by Django 5.2 on 2025-04-15 10:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deadline", models.DateTimeField(null=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "priority",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Critical"),
                            (2, "Important"),
                            (3, "Normal"),
                            (4, "Low"),
                        ],
                        default=4,
                    ),
                ),
                ("assigners", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                (
                    "task_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tasktype"
                    ),
                ),
            ],
            options={
                "ordering": (
                    "is_completed",
                    models.OrderBy(models.F("deadline"), nulls_last=True),
                    "priority",
                ),
                "default_related_name": "tasks",
            },
        ),
    ]
