# Generated by Django 5.2 on 2025-07-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_tasklog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
