# Generated by Django 5.2 on 2025-07-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_tasklog_id"),
        ("core", "0005_tasklog_fields"),
    ]

    operations = []
